### ISSUE TITLE
Dig.py does not work with truth machine program that should work (unless im making a mistake)

### ISSUE THREAD

**Issue by ItzzCode** [bangyen/esolangs#3]
![image](https://user-images.githubusercontent.com/51547168/112228110-1f235100-8c07-11eb-860b-20e86ce6bd43.png)
I can't find issues with this itself, so could you see if you or I are making a mistake?

I've checked the program through, can't find a mistake.

**Comment by bangyen** [comment]
For commands such as `$`, The language specification doesn't mention where to check for numbers, so my code checks the characters north, east, south, and west of the original character. It then uses the first numeric character, which, in the case of the second `$` command in the second line, is a `1` instead of a `2`. As a result, the mole resurfaces right before printing.

EDIT: After a second read, the language specification mentions the order that my code uses:
> Interpreters when faced with more than one value next to “#”, “$”, or “%” should prefer use up, right, down, left.

**Comment by ItzzCode** [comment]
> Interpreters when faced with more than one value next to “#”, “$”, or “%” should prefer use up, right, down, left.

> above, to the left of, below, and to the right

?

**Comment by bangyen** [comment]
Oh whoops, I misspoke. I meant what is mentioned in the language specification.

**Comment by ItzzCode** [comment]
Aight, got it!
